service: coffee-maker

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-2
  memorySize: 128
  timeout: 10
  environment:
    IOT_ENDPOINT: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}.IOT_ENDPOINT}
    SLACK_WEBHOOK: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}.SLACK_WEBHOOK}
    THING_NAME: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}.THING_NAME}

functions:
  notifier:
    handler: bin/coffeestatechange
    events:
      - iot:
          sql: "SELECT * FROM '$aws/things/${file(./serverless.env.yml):${opt:stage, self:provider.stage}.THING_NAME}/shadow/update/accepted' WHERE isUndefined(state.reported.coffee) = false"
          sqlVersion: "beta"
  slackwebhook:
    handler: bin/slackwebhook
    timeout: 3
    events:
      - http: POST slackwebhook

package:
  exclude:
    - ./**
  include:
    - ./bin/**